name: flutter_poc_fingerprint
description: Privacy-safe device and referral attributes POC for Android, iOS, and Flutter Web.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  device_info_plus: ^11.5.0
  universal_web: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
